### ISSUE TITLE
Add support for `gcloud emulators spanner stop`

### ISSUE THREAD

**Issue by aderk** [GoogleCloudPlatform/cloud-spanner-emulator#39] opened 2021-09-21 20:38 UTC
Currently there is no way to stop the emulator outside of finding the process and sending unix signals

**Comment by nielm** [comment] 2022-01-18 11:02
+1

If run interactively via gcloud, CTRL-C in the process shuts down the emulator and subprocesses cleanly. 
```
gcloud emulators spanner start
...
^C
Command killed by keyboard interrupt
$ ps -x | grep spanner_emulator\\/
```

However, killing the gcloud process with -INT -HUP or -TERM does not do this clean shutdown, leaving emulator_main and gateway_main processes still running, which makes it difficult to programmatically start up and shut down the emulator for testing.

 ```
$ gcloud emulators spanner start &
[1] 2314084
...
$ kill 2314084
[1]+  Terminated              gcloud emulators spanner start
...
$ ps -x | grep spanner_emulator\\/
2314115 pts/2    Sl     0:00 /usr/lib/google-cloud-sdk/bin/cloud_spanner_emulator/gateway_main --hostname localhost --grpc_port 9010 --http_port 9020
2314121 pts/2    Sl     0:00 /usr/lib/google-cloud-sdk/bin/cloud_spanner_emulator/emulator_main --host_port localhost:9010
```

These processes must be found and killed manually.

**Comment by gauravpurohit06** [comment] 2022-09-23 08:09
Closing it as the issue is already been tracked on https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/issues/62

**Closed by gauravpurohit06** 2022-09-23 08:09 UTC
