### ISSUE TITLE
Inserts can fail for tables using Spanner generated sequence default values for primary key/uniquely constrained columns

### ISSUE THREAD

**Issue by drewthor** [GoogleCloudPlatform/cloud-spanner-emulator#179] opened 2024-08-13 16:09 UTC
The emulator appears to use a static `absl::flat_hash_map` for sequence tracking to get the next value; this data structure is not thread-safe, so as a race condition, inserts that rely on the next sequence value for the default value of a column that has a unique constraint (e.g. primary key) may fail.

e.g. with the following DDL and then DML executed concurrently there is a race condition that may error
DDL
```
CREATE SEQUENCE IF NOT EXISTS test_id OPTIONS (sequence_kind='bit_reversed_positive');
CREATE TABLE IF NOT EXISTS test_sequence (
    id INT64 NOT NULL DEFAULT (GET_NEXT_SEQUENCE_VALUE(SEQUENCE test_id)),
    value INT64 NOT NULL
) PRIMARY KEY(id);
```

DML
```
INSERT INTO test_sequence (value) VALUES (1), (2), (3), (4)
```

Error (as returned from https://github.com/googleapis/go-sql-spanner)
```
spanner: code = "AlreadyExists", desc = "Failed to insert row with primary key ({pk#id:7205759403792793600}) due to previously existing row
```

Note: This issue is isolated to just the emulator; Cloud Spanner does not have this issue.

**Comment by olavloite** [comment] 2024-08-19 14:53
A fix for this problem will be included in the next emulator release.

**Comment by drewthor** [comment] 2024-09-10 16:07
@olavloite testing this on the latest emulator (both the docker image and the latest binary), we are still seeing frequent `AlreadyExists` errors. `err="spanner: code = \"AlreadyExists\", desc = \"Failed to insert row with primary key ({pk#id:5728578726015270912}) due to previously existing row\""`

**Comment by drewthor** [comment] 2024-09-10 16:39
The `AlreadyExists` errors get more and more frequent on new database connections.

Here is a bit of an improved replication code (run it several times, 2 or 3 should do it, and the errors get more and more frequent):
```go
package main

import (
	"cloud.google.com/go/spanner"
	database "cloud.google.com/go/spanner/admin/database/apiv1"
	"cloud.google.com/go/spanner/admin/database/apiv1/databasepb"
	instance "cloud.google.com/go/spanner/admin/instance/apiv1"
	"cloud.google.com/go/spanner/admin/instance/apiv1/instancepb"
	"context"
	"database/sql"
	"errors"
	"fmt"
	_ "github.com/googleapis/go-sql-spanner"
	"google.golang.org/grpc/codes"
	"log/slog"
	"os"
	"os/signal"
	"sync"
	"time"
)

func main() {
	err := runSequence()
	if err != nil {
		fmt.Fprint(os.Stderr, err)
		os.Exit(1)
	}
}

func runSequence() error {
	ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt)
	defer cancel()

	const (
		ProjectID, InstanceID, DatabaseName = "your-project-id", "test-instance", "test-db"

		Database = "projects/" + ProjectID + "/instances/" + InstanceID + "/databases/" + DatabaseName
	)

	if err := createInstanceAndDatabase(ctx, ProjectID, InstanceID, DatabaseName); err != nil {
		return fmt.Errorf("failed to create instance and database: %w", err)
	}

	db, err := openDatabaseConnSequence(ctx, "projects/"+ProjectID+"/instances/"+InstanceID+"/databases/"+DatabaseName)
	if err != nil {
		return fmt.Errorf("failed to open database connection: %w", err)
	}
	defer db.Close()

	numVals := 10000
	numWorkers := 2

	worker := func(ctx context.Context, wg *sync.WaitGroup, valChan <-chan int, errorChan chan<- error) {
		defer wg.Done()
		for val := range valChan {
			valCtx, valCancel := context.WithTimeout(ctx, 3*time.Second)
			var id int64
			tx, err := db.BeginTx(valCtx, nil)
			if err != nil {
				errorChan <- fmt.Errorf("failed to start transaction: %w", err)
				valCancel()
				continue
			}
			if err := tx.QueryRowContext(valCtx, "INSERT INTO test_sequence (value) VALUES (?) THEN RETURN id", val).Scan(&id); err != nil {
				if !errors.Is(err, context.Canceled) {
					errorChan <- err
					tx.Rollback()
					valCancel()
					continue
				}
			}
			tx.Commit()
			fmt.Println("inserted sequence id:", id)
			valCancel()
		}
	}

	wg := &sync.WaitGroup{}
	wg.Add(numWorkers)

	valChan := make(chan int, numVals)
	errorChan := make(chan error)

	for i := 0; i < numWorkers; i++ {
		go worker(ctx, wg, valChan, errorChan)
	}

	for i := 0; i < numVals; i++ {
		valChan <- i
	}
	close(valChan)

	go func() {
		wg.Wait()
		close(errorChan)
	}()

	for err := range errorChan {
		slog.Error("could not insert value", slog.Any("err", err.Error()))
	}

	return nil
}

func createInstanceAndDatabase(ctx context.Context, projectID, instanceID, databaseName string) error {
	{ // create a new instance
		admin, err := instance.NewInstanceAdminClient(ctx)
		if err != nil {
			return fmt.Errorf("failed to create instance admin: %w", err)
		}
		op, err := admin.CreateInstance(ctx, &instancepb.CreateInstanceRequest{
			Parent:     "projects/" + projectID,
			InstanceId: instanceID,
		})
		if err != nil {
			if spanner.ErrCode(err) == codes.AlreadyExists {
				goto instanceReady
			}
			admin.Close()
			return fmt.Errorf("create instance failed: %w", err)
		}
		if _, err := op.Wait(ctx); err != nil {
			admin.Close()
			return fmt.Errorf("failed to wait instance creation: %w", err)
		}

	instanceReady:
		if err := admin.Close(); err != nil {
			return fmt.Errorf("failed to close instance admin: %w", err)
		}
	}

	{ // create a database
		admin, err := database.NewDatabaseAdminClient(ctx)
		if err != nil {
			return fmt.Errorf("failed to create database admin: %w", err)
		}

		ddl, err := admin.CreateDatabase(ctx, &databasepb.CreateDatabaseRequest{
			Parent:          "projects/" + projectID + "/instances/" + instanceID,
			CreateStatement: "CREATE DATABASE " + "`" + databaseName + "`",
			ExtraStatements: []string{},
			DatabaseDialect: databasepb.DatabaseDialect_GOOGLE_STANDARD_SQL,
		})
		if err != nil {
			if spanner.ErrCode(err) == codes.AlreadyExists {
				goto databaseReady
			}
			admin.Close()
			return fmt.Errorf("failed to create database: %w", err)
		}

		if _, err := ddl.Wait(ctx); err != nil {
			admin.Close()
			return fmt.Errorf("failed to wait database creation: %w", err)
		}

	databaseReady:
		updateReq := &databasepb.UpdateDatabaseDdlRequest{
			Database: "projects/" + projectID + "/instances/" + instanceID + "/databases/" + databaseName,
			Statements: []string{
				`CREATE SEQUENCE IF NOT EXISTS test_id OPTIONS (sequence_kind='bit_reversed_positive')`,
				`CREATE TABLE IF NOT EXISTS test_sequence (
    			id INT64 NOT NULL DEFAULT (GET_NEXT_SEQUENCE_VALUE(SEQUENCE test_id)),
    			value INT64 NOT NULL
			) PRIMARY KEY(id)`,
			},
		}

		updateDDL, err := admin.UpdateDatabaseDdl(ctx, updateReq)
		if err != nil {
			admin.Close()
			return fmt.Errorf("failed to update database ddl: %w", err)
		}
		if err := updateDDL.Wait(ctx); err != nil {
			admin.Close()
			return fmt.Errorf("failed to wait for database ddl: %w", err)
		}

		if err := admin.Close(); err != nil {
			return fmt.Errorf("failed to close database admin: %w", err)
		}

	}
	return nil
}

func openDatabaseConnSequence(ctx context.Context, databaseConn string) (*sql.DB, error) {
	db, err := sql.Open("spanner", databaseConn)
	if err != nil {
		return nil, fmt.Errorf("failed to open connection to db: %w", err)
	}

	return db, nil
}
```

**Comment by hengfengli** [comment] 2024-09-11 11:36
Hi @drewthor, thanks a lot for providing the reproducing code. With your code, we have identified the root cause. This is not a concurrency issue. We have a bug that when the sequence `test_id` already exists, calling `CREATE SEQUENCE IF NOT EXISTS test_id OPTIONS (sequence_kind='bit_reversed_positive')` would cause a deletion of the recorded last value (the state) for the sequence `test_id`. Therefore, if you do: 

```
// Update DDL (reset the last value to the default value)
CREATE SEQUENCE IF NOT EXISTS test_id OPTIONS (sequence_kind='bit_reversed_positive')

// Inserts
insert data
```

Every time when you re-run the program, it resets the recorded value to 1 and then, starts inserting data. If you can avoid updating DDL every time (only calling CREATE SEQUENCE once), it should avoid the above error. In the meanwhile, we are working on a fix to this issue.

**Comment by drewthor** [comment] 2024-09-26 23:30
@hengfengli thanks for the release! I have verified that the actual production program does not perform DDL more than once and even after the latest update still occasionally sees inserts to a table with an emulator-generated sequence primary key error with code `AlreadyExists` and an explanation that the primary key, which is an emulator-generated bit-reversed sequence, already exists (there are no other unique indexes on the table).

I am trying to produce a sharable code snippet that mimics what is performed in production and that can at least somewhat reliably reproduce the issue. It is a flakey issue and as such is hard to pin down.

**Comment by egonelbre** [comment] 2024-09-30 13:44
Here's my best attempt at creating a reliable reproducer.

<details>

``` go
package main

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"os/signal"
	"sync"
	"sync/atomic"

	"cloud.google.com/go/spanner"
	database "cloud.google.com/go/spanner/admin/database/apiv1"
	"cloud.google.com/go/spanner/admin/database/apiv1/databasepb"
	instance "cloud.google.com/go/spanner/admin/instance/apiv1"
	"cloud.google.com/go/spanner/admin/instance/apiv1/instancepb"
	_ "github.com/googleapis/go-sql-spanner"
	"google.golang.org/grpc/codes"
)

func main() {
	err := runSequence()
	if err != nil {
		fmt.Fprint(os.Stderr, err)
		os.Exit(1)
	}
}

func runSequence() error {
	ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt)
	defer cancel()

	const (
		ProjectID, InstanceID = "proj", "inst"

		Parallel       = 10
		Repeats        = 10
		BatchesPerDB   = 10
		ValuesPerBatch = 5
	)

	var dbindex atomic.Int64

	var wg sync.WaitGroup

	for range Parallel {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for range Repeats {
				func() {
					databaseName := fmt.Sprintf("db%v", dbindex.Add(1))
					must(0, createInstanceAndDatabase(ctx, ProjectID, InstanceID, databaseName))

					db := must(openDatabaseConnSequence(ctx, "projects/"+ProjectID+"/instances/"+InstanceID+"/databases/"+databaseName+"?maxsessions=10000"))
					defer func() { must(0, db.Close()) }()

					for range BatchesPerDB {
					retry:
						tx, err := db.BeginTx(ctx, nil)
						if err != nil {
							if spanner.ErrCode(err) == codes.Aborted {
								goto retry
							}
							panic(err)
						}

						for i := range ValuesPerBatch {
							_, err := tx.ExecContext(ctx, `INSERT INTO test_sequence (value) VALUES (?)`, i)
							if err != nil {
								_ = tx.Rollback()
								if spanner.ErrCode(err) == codes.Aborted {
									goto retry
								}
								panic(err)
							}
						}

						must(0, tx.Commit())
					}
				}()
			}
		}()
	}

	wg.Wait()

	return nil
}

func createInstanceAndDatabase(ctx context.Context, projectID, instanceID, databaseName string) error {
	{ // create a new instance
		admin, err := instance.NewInstanceAdminClient(ctx)
		if err != nil {
			return fmt.Errorf("failed to create instance admin: %w", err)
		}
		op, err := admin.CreateInstance(ctx, &instancepb.CreateInstanceRequest{
			Parent:     "projects/" + projectID,
			InstanceId: instanceID,
		})
		if err != nil {
			if spanner.ErrCode(err) == codes.AlreadyExists {
				goto instanceReady
			}
			admin.Close()
			return fmt.Errorf("create instance failed: %w", err)
		}
		if _, err := op.Wait(ctx); err != nil {
			admin.Close()
			return fmt.Errorf("failed to wait instance creation: %w", err)
		}

	instanceReady:
		if err := admin.Close(); err != nil {
			return fmt.Errorf("failed to close instance admin: %w", err)
		}
	}

	{ // create a database
		admin, err := database.NewDatabaseAdminClient(ctx)
		if err != nil {
			return fmt.Errorf("failed to create database admin: %w", err)
		}

		ddl, err := admin.CreateDatabase(ctx, &databasepb.CreateDatabaseRequest{
			Parent:          "projects/" + projectID + "/instances/" + instanceID,
			CreateStatement: "CREATE DATABASE " + "`" + databaseName + "`",
			ExtraStatements: []string{},
			DatabaseDialect: databasepb.DatabaseDialect_GOOGLE_STANDARD_SQL,
		})
		if err != nil {
			if spanner.ErrCode(err) == codes.AlreadyExists {
				goto databaseReady
			}
			admin.Close()
			return fmt.Errorf("failed to create database: %w", err)
		}

		if _, err := ddl.Wait(ctx); err != nil {
			admin.Close()
			return fmt.Errorf("failed to wait database creation: %w", err)
		}

	databaseReady:
		updateReq := &databasepb.UpdateDatabaseDdlRequest{
			Database: "projects/" + projectID + "/instances/" + instanceID + "/databases/" + databaseName,
			Statements: []string{
				`CREATE SEQUENCE IF NOT EXISTS test_id OPTIONS (sequence_kind='bit_reversed_positive')`,
				`CREATE TABLE IF NOT EXISTS test_sequence (
					id INT64 NOT NULL DEFAULT (GET_NEXT_SEQUENCE_VALUE(SEQUENCE test_id)),
					value INT64 NOT NULL
				) PRIMARY KEY(id)`,
			},
		}

		updateDDL, err := admin.UpdateDatabaseDdl(ctx, updateReq)
		if err != nil {
			admin.Close()
			return fmt.Errorf("failed to update database ddl: %w", err)
		}
		if err := updateDDL.Wait(ctx); err != nil {
			admin.Close()
			return fmt.Errorf("failed to wait for database ddl: %w", err)
		}

		if err := admin.Close(); err != nil {
			return fmt.Errorf("failed to close database admin: %w", err)
		}

	}
	return nil
}

func openDatabaseConnSequence(ctx context.Context, databaseConn string) (*sql.DB, error) {
	db, err := sql.Open("spanner", databaseConn)
	if err != nil {
		return nil, fmt.Errorf("failed to open connection to db: %w", err)
	}

	return db, nil
}

func must[T any](v T, err error) T {
	if err != nil {
		panic(err)
	}
	return v
}
```

</details>

The main idea is to create the same database schema in parallel, but with different database names. And with each database try inserting into a table which has `(GET_NEXT_SEQUENCE_VALUE(SEQUENCE test_id))`, with that specific id as the primary key. That quite quickly ends up in a:

```
panic: spanner: code = "AlreadyExists", desc = "Failed to insert row with primary key ({pk#id:4611686018427387904}) due to previously existing row"
```

This implies that that a database creation can end up causing a reset on some other database sequences.

_(Of course assuming that I didn't make some obvious mistake)_

**Comment by egonelbre** [comment] 2024-09-30 13:59
If I change the test code above to use unique sequence names per database, then it passes, e.g:

``` go
		updateReq := &databasepb.UpdateDatabaseDdlRequest{
			Database: "projects/" + projectID + "/instances/" + instanceID + "/databases/" + databaseName,
			Statements: []string{
				`CREATE SEQUENCE IF NOT EXISTS test_id_` + databaseName + ` OPTIONS (sequence_kind='bit_reversed_positive')`,
				`CREATE TABLE IF NOT EXISTS test_sequence (
					id INT64 NOT NULL DEFAULT (GET_NEXT_SEQUENCE_VALUE(SEQUENCE test_id_` + databaseName + `)),
					value INT64 NOT NULL
				) PRIMARY KEY(id)`,
			},
		}
```

**Comment by egonelbre** [comment] 2024-12-04 12:54
Looks like v1.5.26 fixes this issue.

**Comment by hengfengli** [comment] 2024-12-08 23:14
Yes, we have made a fix for this issue. Please let us know if you have any further issues.

**Closed by hengfengli** 2024-12-08 23:14 UTC
