### ISSUE TITLE
DDL case sensitivity

### ISSUE THREAD

**Issue by lawt3** [GoogleCloudPlatform/cloud-spanner-emulator#108] opened 2023-03-24 03:08 UTC
I've noticed that Spanner Emulator is more lenient with table name case than Spanner which has caused a few issues to slip past CI.

For example, imagine Spanner contains a table named `Account`. The statement:
```sql
ALTER TABLE ACCOUNT ADD COLUMN Test BOOL
```
runs successfully in the emulator and adds the column to the `Account` table. However, running the statement against Spanner fails with the error `Table ACCOUNT not found`.

Per the [docs](https://cloud.google.com/spanner/docs/reference/standard-sql/data-definition-language#naming_conventions), 
> When referring to other schema objects in a DDL statement (for example, a column name for a primary key, or table and column names in an index), make sure to use the original case for the name of each entity.

so the emulator should error in this case.

**Comment by fenilfadadu** [comment] 2023-05-24 03:04
The issue is fixed and should be available in the next emulator release.

**Comment by fenilfadadu** [comment] 2023-05-29 06:38
Fix has been integrated into the latest emulator release. Closing it.

**Closed by fenilfadadu** 2023-05-29 06:38 UTC
