### ISSUE TITLE
default ordering of rows is different from live product

### ISSUE THREAD

**Issue by gsouf** [GoogleCloudPlatform/cloud-spanner-emulator#14] opened 2020-11-26 20:01 UTC
Emulator and live product do not apply the same default sorting of records (when no `ORDER BY` is specified, or when multiple rows have the same value for the `ORDER BY` clause).

Here is how to replicate:

```
gcloud spanner instances create test-order \
  --config=emulator-config \
  --description="Test Instance" \
  --nodes=1

gcloud spanner databases create test \
 --instance=test-order \
 --ddl="CREATE TABLE test (a INT64, b INT64, c INT64,) PRIMARY KEY (a, b)"

gcloud spanner databases execute-sql test \
 --instance=test-order \
 --sql="INSERT test(a, b, c) VALUES (2, 1, 3), (2, 2, 3), (1, 2, 4)"

gcloud spanner databases execute-sql test \
 --instance=test-order \
 --sql="SELECT * FROM test"
```

Emulator returs:
```
a  b  c
2  1  3
1  2  4
2  2  3
```

Live returns:
```
a  b  c
1  2  4
2  1  3
2  2  3
```

-----

Now order by `a`:

```
gcloud spanner databases execute-sql test \
 --instance=test-order \
 --sql="SELECT * FROM test ORDER BY a ASC"
```

Emulator returs:
```
a  b  c
1  2  4
2  2  3
2  1  3
```

Live returns:
```
a  b  c
1  2  4
2  1  3
2  2  3
```

**Comment by Vizerai** [comment] 2020-11-30 22:59
The ordering of results is not guaranteed without the use of an ORDER BY clause in the emulator.

If you use an ORDER BY clause on both columns you get the expected result:
```
gcloud spanner databases execute-sql test  --instance=test-order  --sql="SELECT * FROM test ORDER BY a ASC, b ASC"
```

```
a  b  c
1  2  4
2  1  3
2  2  3
```

**Comment by adirastogi** [comment] 2020-12-01 12:14
This is also noted in the [FAQs section](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator#why-is-the-order-of-rows-returned-by-the-emulator-different-across-runs)  on the README page. Marking this issue as closed as this is working as intended.

**Closed by adirastogi** 2020-12-01 12:14 UTC

**Comment by gsouf** [comment] 2020-12-01 12:19
@adirastogi I understand this but it makes it hard to maintain our unit tests that don't use an order by accross real product and emulator, as the live product will always sort data by primary key.

**Comment by adirastogi** [comment] 2020-12-01 13:07
The emulator intentionally re-orders the rows in response to a query without an `ORDER BY` because the Cloud Spanner service doesn't guarantee it (even though that property of the production service is very unlikely to change).  You'll see that in a few other areas as well - different order of evaluation of predicates, random aborts in transactions etc. The idea is to discourage users/clients to write application code that can be a Cloud Spanner anti-pattern or relies on undocumented behavior of the service. Catching such bad practices during app development or testing is much better than dealing with them in production.

For your specific case, a common solution is to do an unordered comparison of the results obtained from Cloud Spanner/Emulator against the expected outcome.

**Comment by gsouf** [comment] 2020-12-01 13:09
@adirastogi I understand this point again, but it's not what I would expect from an emulator and I guess it's going to be an unpopular feature of the emulator
